version: '3.8'

services:
  # 웹 애플리케이션 서비스
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    restart: unless-stopped

  # MongoDB 데이터베이스 서비스
  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # Redis 캐시 서비스
  redis:
    image: redis:7-alpine
    ports:
      - "3797:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

# 볼륨 정의
volumes:
  mongodb_data:
  redis_data:
